name: Black Code Formatter

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main, master ]
  # Also trigger on pull requests to these branches
  pull_request:
    branches: [ main, master ]

# The actual jobs that will run
jobs:
  formatting:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed
    steps:
    # Checkout the repository code
    - uses: actions/checkout@v5

    # Set up Python (choose the version that matches your project)
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    # Install Black
    - name: Install Black
      run: |
        python -m pip install --upgrade pip
        pip install black==24.10.0

    # Run Black and check formatting
    - name: Run Black
      run: black --check .
